public enum WSSMessageIDs : byte
{
    Error =0x05,
    ModuleQuery = 0x01,
    Reset = 0x04,
    Echo = 0x07,
    RequestAnalog = 0x02,
    Clear = 0x40,
    RequestConfig = 0x41,
    CreateContactConfig = 0x42,
    DeleteContactConfig = 0x43,
    CreateEvent = 0x44,
    DeleteEvent = 0x45,
    AddEventToSchedule = 0x46,
    RemoveEventFromSchedule = 0x47,
    MoveEventToSchedule = 0x48,
    EditEventConfig = 0x49,
    CreateSchedule = 0x4A,
    DeleteSchedule = 0x4B,
    SyncGroup = 0x4C,
    ChangeGroupState = 0x4D,
    ChangeScheduleConfig = 0x4E,
    ResetSchedule = 0x4F,
    CustomWaveform = 0x9D,
    StimulationSwitch = 0x0B,
    BoardCommands = 0x09,
    StreamChangeAll = 0x30,
    StreamChangeNoIPI = 0x31,
    StreamChangeNoPA = 0x33,
    StreamChangeNoPW = 0x32,
}
